// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: todo_api.proto

// Protobuf Java Version: 3.25.1
package com.redbirdcodes.todo.api.grpc;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:todo.Empty)
    com.google.protobuf.MessageOrBuilder {
}
