// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: todo_api.proto

// Protobuf Java Version: 3.25.1
package com.redbirdcodes.todo.api.grpc;

public interface IdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:todo.Id)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();
}
