// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: todo_api.proto

// Protobuf Java Version: 3.25.1
package com.redbirdcodes.todo.api.grpc;

public final class TodoApi {
  private TodoApi() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_todo_Id_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_todo_Id_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_todo_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_todo_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_todo_ToDo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_todo_ToDo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016todo_api.proto\022\004todo\"\020\n\002Id\022\n\n\002id\030\001 \001(\003" +
      "\"\007\n\005Empty\"F\n\004ToDo\022\n\n\002id\030\001 \001(\003\022\r\n\005title\030\002" +
      " \001(\t\022\023\n\013description\030\003 \001(\t\022\016\n\006status\030\004 \001(" +
      "\t2\315\001\n\007ToDoApi\022!\n\007GetToDo\022\010.todo.Id\032\n.tod" +
      "o.ToDo\"\000\022(\n\tListToDos\022\013.todo.Empty\032\n.tod" +
      "o.ToDo\"\0000\001\022%\n\010SaveToDo\022\n.todo.ToDo\032\013.tod" +
      "o.Empty\"\000\022\'\n\nUpdateToDo\022\n.todo.ToDo\032\013.to" +
      "do.Empty\"\000\022%\n\nDeleteToDo\022\010.todo.Id\032\013.tod" +
      "o.Empty\"\000B\"\n\036com.redbirdcodes.todo.api.g" +
      "rpcP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_todo_Id_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_todo_Id_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_todo_Id_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_todo_Empty_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_todo_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_todo_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_todo_ToDo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_todo_ToDo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_todo_ToDo_descriptor,
        new java.lang.String[] { "Id", "Title", "Description", "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
